// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutorManager creates a new instance of MockExecutorManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutorManager[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutorManager[T] {
	mock := &MockExecutorManager[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutorManager is an autogenerated mock type for the ExecutorManager type
type MockExecutorManager[T any] struct {
	mock.Mock
}

type MockExecutorManager_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockExecutorManager[T]) EXPECT() *MockExecutorManager_Expecter[T] {
	return &MockExecutorManager_Expecter[T]{mock: &_m.Mock}
}

// Executor provides a mock function for the type MockExecutorManager
func (_mock *MockExecutorManager[T]) Executor() T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Executor")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func() T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// MockExecutorManager_Executor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Executor'
type MockExecutorManager_Executor_Call[T any] struct {
	*mock.Call
}

// Executor is a helper method to define mock.On call
func (_e *MockExecutorManager_Expecter[T]) Executor() *MockExecutorManager_Executor_Call[T] {
	return &MockExecutorManager_Executor_Call[T]{Call: _e.mock.On("Executor")}
}

func (_c *MockExecutorManager_Executor_Call[T]) Run(run func()) *MockExecutorManager_Executor_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutorManager_Executor_Call[T]) Return(v T) *MockExecutorManager_Executor_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockExecutorManager_Executor_Call[T]) RunAndReturn(run func() T) *MockExecutorManager_Executor_Call[T] {
	_c.Call.Return(run)
	return _c
}
